github/search-repos: Clean up the method, add a couple of flags, and provide more inline context about usage and requirements.

diff --git a/bin/utilities/github/search-repos b/bin/utilities/github/search-repos
--- a/bin/utilities/github/search-repos
+++ b/bin/utilities/github/search-repos
@@ -1,47 +1,105 @@
 #!/usr/bin/env bash
 set -e
-[[ -f ${DOTFILES_PATH}/bash/helpers.sh ]] && source ${DOTFILES_PATH}/bash/helpers.sh
-[[ ! `command -v jq` ]] && brew install jq
 
-# TODO: Probably better to rename this to github-lookup-repos.
+# Gracefully handle Ctrl-C to get out of this thing.
+handle_interrupt() {
+  echo "Aborted."
+  exit 1
+}
+trap handle_interrupt SIGINT
 
 # This command is used to provide suggestions among both my personal as well as
-# my work's public ànd private repositories.
-#
-# To access private repositories you will need a GitHub auth token with the
-# "repo" scope. You can request one here: https://github.com/settings/tokens.
-# Export it to an ENV var called GITHUB_API_TOKEN.
-#
-# The obvious shortcoming here is the fact that the per_page limit has a
-# ceiling of 100.
+# my work's public and private repositories.
 
-if [[ -z $GITHUB_API_TOKEN ]]; then
-  echo "ERROR: No personalized access token set."
-  printf "\t1. Create one here: https://github.com/settings/tokens\n"
-  printf "\t2. Put 'export GITHUB_API_TOKEN=<access-token>' in your ~/.bash_profile\n"
+[[ -f ${DOTFILES_PATH}/bash/helpers.sh ]] && source ${DOTFILES_PATH}/bash/helpers.sh
+[[ ! $(command -v jq) ]] && brew install jq
+
+# Access to private repositories will require a Github access token with the
+# "repo" scope.
+if [[ -z $GITHUB_PERSONAL_ACCESS_TOKEN ]]; then
+  echo "ERROR: No Github personal access token set."
+  echo ""
+  echo "  1. Create one here: https://github.com/settings/tokens"
+  echo ""
+  echo "  2. Make sure the token has access to the 'repo' scope."
+  echo "     (This means full read-only access to private repositories)"
+  echo ""
+  echo "  3. Store it in GITHUB_PERSONAL_ACCESS_TOKEN and make sure it's available."
+  echo ""
   exit 1
 fi
 
-if [[ -z $1 ]]; then
-  echo 'ERROR: No search query namespace given.'
-  printf "\tUsage: git search-repos user:davelens+user:blimp\n"
-  exit 2
-fi
+usage() {
+  echo "Usage: utility github $(basename $0) <qualifier>"
+  echo ""
+  echo "Arguments:"
+  echo "  -h|--help            Show this help message and exit."
+  echo "  -v|--verbose         Enable verbose output for curl calls."
+  echo "  <qualifier>          The Github-specific search qualifier to filter the results."
+  echo "                       (e.g. 'Phoenix Framework', 'author:johndoe', 'user:johndoe+user:maryjane', ...)"
+  echo ""
+  echo ""
+  echo "You can read up on Github search qualifiers for repositories here:"
+  echo ""
+  echo "  https://github.com/github/docs/blob/main/content/search-github/searching-on-github/searching-for-repositories.md"
+  echo ""
+  exit 0
+}
 
-declare query=$1
-declare -i page=1
-declare -a results
+# Fail early if no arguments are given.
+[[ $# -eq 0 ]] && usage
 
+verbal=false
+query=""
+page=1
+results=()
+
+while [[ $# -gt 0 ]]; do
+  case "$1" in
+    -h|--help)
+      usage
+      ;;
+    -v|--verbal)
+      verbal=true
+      shift
+      ;;
+    *)
+      query="$1"
+      shift
+      ;;
+  esac
+done
+
+# No query, no results.
+[[ -z $query ]] && usage
+
+# Sanitize the query for use in the Github API call. 
+# Only spaces are a problem, for now.
+query=$(echo "${query// /+}")
+
+# Recursively search for repositories.
 search() {
-  local repositories=($(curl -s --header "Authorization: token $GITHUB_API_TOKEN" --url "https://api.github.com/search/repositories?q=$query&per_page=100&page=$page" | jq -r '.items[] .full_name'))
+  local url="https://api.github.com/search/repositories?q=$query&per_page=100&page=$page"
+
+  # Print out the requests if verbal mode is enabled.
+  $verbal && echo "GET $url"
+
+  local repositories=($(curl -s --header "Authorization: token $GITHUB_PERSONAL_ACCESS_TOKEN" --url "$url" | jq -r 'try .items[] .full_name'))
 
   results=("${results[@]}" "${repositories[@]}")
 
-  if [[ ${#repositories[@]} == 100 ]]; then
-    page+=1
+  if [[ ${#repositories[@]} -eq 100 ]]; then
+    ((page++))
     search
   fi
 }
 
+# Perform the initial search
+# Notify the user in verbose mode when we start polling Github.
+$verbal && echo "Collecting data from Github ... "
 search
-for repo in ${results[@]}; do echo $repo; done | fzf
+
+# Output results to fzf for selection, and Bob's your uncle.
+for repo in "${results[@]}"; do
+  echo "$repo"
+done | fzf
