utilities/docker: Add `mysql` autocompletion for databases + allow redirection to stdin with default completion active (so you can do `u docker mysql raamwinkel_dev < latest.sql`).

diff --git a/bin/utilities/docker/mysql b/bin/utilities/docker/mysql
--- a/bin/utilities/docker/mysql
+++ b/bin/utilities/docker/mysql
@@ -1,7 +1,13 @@
 #!/usr/bin/env bash
 set -e
 
-[ ! $(command -v docker) ] && fail "ERROR: Docker is not installed."
-docker info &> /dev/null || fail "ERROR: Docker is not running."
+! command_exists 'docker' && fail "ERROR: Docker is not installed."
+docker info &>/dev/null || fail "ERROR: Docker is not running."
 
-mysql -h localhost -P 3306 --protocol=tcp
+database="${1:-}"
+
+if [[ -n "$database" ]]; then
+  mysql -h localhost -P 3306 --protocol=tcp "$database"
+else
+  mysql -h localhost -P 3306 --protocol=tcp
+fi
