Be consistent in ${} usage. Don't use it "just because".

diff --git a/bin/utilities/bash/cursor b/bin/utilities/bash/cursor
--- a/bin/utilities/bash/cursor
+++ b/bin/utilities/bash/cursor
@@ -10,7 +10,7 @@ name="cursor"
 
 #
 # Note: the [-p|--for-prompt] option is specific to my dotfiles.
-# I wouldn't know how to go about calculating the bash prompt height. 
+# I wouldn't know how to go about calculating the bash prompt height.
 # I know in my case it's always 2.
 #
 # I suppose it could be a bit more flexible by reading the deficit value
@@ -19,7 +19,7 @@ name="cursor"
 usage() {
   echo
   echo "Usage: $name [-h|--help] <command(s)>"
-  echo 
+  echo
   echo "Move the cursor around the terminal quickly by chaining commands."
   echo
   echo "Examples:"
@@ -57,19 +57,19 @@ usage() {
 ###############################################################################
 
 declare -A sequences=(
-  ["move_start"]='033[G'
-  ["move_up"]='033[${steps}A'
-  ["move_down"]='033[${steps}B'
-  ["move_right"]='033[${steps}C'
-  ["move_left"]='033[${steps}D'
-  ["clear_down"]='033[0J'
-  ["clear_right"]='033[0K'
-  ["clear_left"]='033[1K'
-  ["clear_line"]='033[2K'
-  ["restore"]='033[u'
-  ["save"]='033[s'
-  ["col"]='033[${steps}G'
-  ["line"]='033[${steps};1H'
+  ["move_start"]="033[G"
+  ["move_up"]="033[\${steps}A"
+  ["move_down"]="033[\${steps}B"
+  ["move_right"]="033[\${steps}C"
+  ["move_left"]="033[\${steps}D"
+  ["clear_down"]="033[0J"
+  ["clear_right"]="033[0K"
+  ["clear_left"]="033[1K"
+  ["clear_line"]="033[2K"
+  ["restore"]="033[u"
+  ["save"]="033[s"
+  ["col"]="033[\${steps}G"
+  ["line"]="033[\$steps;1H"
 )
 
 # Dynamically create methods
@@ -82,29 +82,29 @@ done
 #############################################################################
 
 function seq_move_end {
-  seq_move_right $(tput cols) 
+  seq_move_right "$(tput cols)"
 }
 
 function seq_move_up {
   local jump=${1:-1}
   [[ $in_prompt -eq 1 ]] && jump=$((jump + $(prompt_correction)))
-  printf "\033[${jump}A"
+  printf "\033[%sA" "$jump"
 }
 
 function seq_move_down {
   local jump=${1:-1}
   [[ $in_prompt -eq 1 ]] && jump=$((jump - $(prompt_correction)))
-  printf "\033[${jump}B"
+  printf "\033[%sB" "$jump"
 }
 
 function seq_clear_up {
   local jump=${1:-1}
-  seq_move_up $jump
+  seq_move_up "$jump"
   seq_clear_down
 }
 
 function seq_print {
-  printf "$steps"
+  printf "%s" "$steps"
 }
 
 ###############################################################################
@@ -121,7 +121,7 @@ function prompt_correction {
 function chain_commands {
   for cmd in ${commands[@]}; do
     command="${cmd%%:*}" # Extract the part before `:`
-    steps=${cmd##*:}   # Extract the part after `:`
+    steps=${cmd##*:}     # Extract the part after `:`
     [[ "$command" == "$steps" ]] && steps=1
     $command $steps
   done
@@ -132,28 +132,28 @@ function chain_commands {
 function main {
   [[ $# -eq 0 ]] && usage && exit 0
 
-  local steps=1 in_prompt=0 raw=0 
+  local steps=1 in_prompt=0 raw=0
   local commands=() options=()
 
-  IFS=' ' read -r -a args <<< "$@"
+  IFS=' ' read -r -a args <<<"$@"
 
   # Isolate commands from options
   for arg in "${args[@]}"; do
-    if [[ $arg =~ ^- ]]; then 
+    if [[ $arg =~ ^- ]]; then
       case $arg in
-        -h | --help) usage && exit 0 ;;
-        -p | --for-prompt) in_prompt=1;;
-        -r | --raw) raw=1;;
-        *)
-          if [[ -z $1 ]]; then
-            $print_status -i error "Invalid options: $arg"
-            usage && exit 1
-          fi
-          ;;
+      -h | --help) usage && exit 0 ;;
+      -p | --for-prompt) in_prompt=1 ;;
+      -r | --raw) raw=1 ;;
+      *)
+        if [[ -z $1 ]]; then
+          $print_status -i error "Invalid options: $arg"
+          usage && exit 1
+        fi
+        ;;
       esac
 
       options+=("$arg")
-    else 
+    else
       commands+=("$arg")
     fi
   done
@@ -164,7 +164,7 @@ function main {
   for ((i = 0; i < ${#commands[@]}; i++)); do
     commands[i]="seq_${commands[i]/-/_}"
 
-    if ! command -v "${commands[i]%%:*}" &> /dev/null; then
+    if ! command -v "${commands[i]%%:*}" &>/dev/null; then
       $print_status -i error "Invalid command: ${commands[i]}"
       usage && exit 1
     fi
diff --git a/bin/utilities/bash/salt b/bin/utilities/bash/salt
--- a/bin/utilities/bash/salt
+++ b/bin/utilities/bash/salt
@@ -11,9 +11,9 @@ name="salt"
 usage() {
   echo
   echo "Usage: $name [-h|--help] <options>"
-  echo 
+  echo
   echo "Operations related to the default salt used in encrypt/decrypt."
-  echo 
+  echo
   echo "Commands:"
   echo "  current               (Re)generate a new salt."
   echo "  reset                 Reset the salt along with all encrypted files."
@@ -54,7 +54,7 @@ function generate {
     passkey=$($prompt_user -i "$icon " -m "Enter your desired password: ") >&2
   fi
 
-  pass_confirmation=$($prompt_user -i "$(pending) " -m  "Confirm your entered password: ") >&2
+  pass_confirmation=$($prompt_user -i "$(pending) " -m "Confirm your entered password: ") >&2
 
   if [[ ${#passkey} -lt 3 ]]; then
     $cursor restore clear-down >&2
@@ -126,25 +126,25 @@ function main {
   local command options passkey
   options=()
 
-  IFS=' ' read -r -a args <<< "$@"
+  IFS=' ' read -r -a args <<<"$@"
 
   for arg in "${args[@]}"; do
-    if [[ $arg =~ ^- ]]; then 
+    if [[ $arg =~ ^- ]]; then
       case "$arg" in
-        -h | --help)
-          usage
-          exit 0
-          ;;
-        -k | --passkey)
-          passkey="$2" 
-          ;;
-        #-s | --silent) silent=1;;
-        -*)
-          if [[ -z $1 ]]; then
-            $print_status -i error "Invalid options: $arg"
-            usage && exit 1
-          fi
-          ;;
+      -h | --help)
+        usage
+        exit 0
+        ;;
+      -k | --passkey)
+        passkey="$2"
+        ;;
+      #-s | --silent) silent=1;;
+      -*)
+        if [[ -z $1 ]]; then
+          $print_status -i error "Invalid options: $arg"
+          usage && exit 1
+        fi
+        ;;
       esac
 
       options+=("$arg")
@@ -154,7 +154,7 @@ function main {
   # Last argument should always be the command.
   command="${@: -1}"
 
-  if ! command -v "$command" &> /dev/null; then
+  if ! command -v "$command" &>/dev/null; then
     $print_status -i error "Invalid command: $command"
     usage && exit 1
   fi
diff --git a/bin/utility b/bin/utility
--- a/bin/utility
+++ b/bin/utility
@@ -4,24 +4,28 @@
 set -e
 export_env_vars_from_file
 
-# Ensure we have at least two arguments
-[[ $# -lt 2 ]] && fail "Usage: $(basename "$0") <category> <command> [<args>...]"
+main() {
+  # Ensure we have at least two arguments
+  [[ $# -lt 2 ]] && fail "Usage: $(basename "$0") <category> <command> [<args>...]"
 
-# Define the base directory for scripts
-BASE_DIR="${DOTFILES_PATH}/bin/utilities"
-CATEGORY="$1"
-COMMAND="$2"
+  local category command
+  category="$1"
+  command="$2"
 
-# Shift off category and command, leaving any remaining arguments
-shift 2
+  # Define the base directory for scripts
+  BASE_DIR="$DOTFILES_PATH/bin/utilities"
+  SCRIPT_PATH="$BASE_DIR/$category/$command"
 
-# Construct the path to the script
-SCRIPT_PATH="$BASE_DIR/$CATEGORY/$COMMAND"
+  # Shift off category and command, leaving any remaining arguments
+  shift 2
 
-# Check if the script exists and is executable
-if [ -x "$SCRIPT_PATH" ]; then
-  "$SCRIPT_PATH" "$@"  # Execute the script with remaining arguments
-else
-  echo "Error: Script '$COMMAND' not found in '$BASE_DIR/$CATEGORY' or not executable."
-  exit 1
-fi
+  # Check if the script exists and is executable
+  if [ -x "$SCRIPT_PATH" ]; then
+    "$SCRIPT_PATH" "$@" # Execute the script with remaining arguments
+  else
+    echo "Error: Script '$command' not found in '$BASE_DIR/$category' or not executable."
+    exit 1
+  fi
+}
+
+main "$@"
diff --git a/setup/dots b/setup/dots
--- a/setup/dots
+++ b/setup/dots
@@ -31,7 +31,7 @@ logs() {
     $EDITOR \
       -c 'set nomodifiable laststatus=0' \
       -c 'highlight WinBarMsg guifg=#ffcc00 guibg=#44475a gui=bold' \
-      -c "lua vim.o.winbar = '%#WinBarMsg#${winbar}'" \
+      -c "lua vim.o.winbar = '%#WinBarMsg#$winbar'" \
       -c 'nnoremap q :q<CR>' \
       -c "nnoremap c :silent !truncate -s 0 '$log_file' \| edit<CR>" \
       -R + "$log_file"
@@ -59,7 +59,7 @@ update() {
   $print_status -n "Pulling in changes ..."
 
   if git -C "$DOTFILES_PATH" fetch origin >/dev/null; then
-    if ! git -C "$DOTFILES_PATH" merge --no-commit origin/"$(git -C "$DOTFILES_PATH" b)" &>> "$log_file"; then
+    if ! git -C "$DOTFILES_PATH" merge --no-commit origin/"$(git -C "$DOTFILES_PATH" b)" &>>"$log_file"; then
       error_occurred=1
     fi
   else
@@ -70,7 +70,7 @@ update() {
   if [ $error_occurred -eq 0 ]; then
     $print_status -i ok "Files updated to latest version"
     $print_status -n "Running installer ..."
-    "$DOTFILES_PATH"/setup/install &>> "$log_file" || error_occurred=1
+    "$DOTFILES_PATH"/setup/install &>>"$log_file" || error_occurred=1
   fi
 
   # Handle final status
@@ -89,20 +89,20 @@ if [[ $# -eq 0 ]]; then
 fi
 
 case "$1" in
-  -h|--help)
-    usage
-    ;;
-  logs)
-    logs
-    ;;
-  install)
-    install
-    ;;
-  update)
-    update
-    ;;
-  *)
-    echo "Unknown command: $1"
-    usage
-    ;;
+-h | --help)
+  usage
+  ;;
+logs)
+  logs
+  ;;
+install)
+  install
+  ;;
+update)
+  update
+  ;;
+*)
+  echo "Unknown command: $1"
+  usage
+  ;;
 esac
