Add a way to have aliases for helper functions used in some of my bash commands, without taking them out of the commands.

diff --git a/bin/utilities/bash/cursor b/bin/utilities/bash/cursor
--- a/bin/utilities/bash/cursor
+++ b/bin/utilities/bash/cursor
@@ -8,7 +8,7 @@
 
 trap 'error_handler' ERR
 
-NAME=$(basename $0)
+NAME=$(basename "$(is_sourced && echo ${BASH_SOURCE[0]} || echo "$0")")
 #
 # Note: the [-p|--for-prompt] option is specific to my dotfiles.
 # I wouldn't know how to go about calculating the bash prompt height. 
@@ -55,10 +55,7 @@ usage() {
   echo "  -r|--raw            Returns the ANSI escape sequence as a string."
 }
 
-# Fail early if no arguments are given.
-[[ $# -eq 0 ]] && usage && exit 1
-
-#############################################################################
+###############################################################################
 
 declare -A sequences=(
   ["move_start"]='033[G'
@@ -111,7 +108,7 @@ function seq_print() {
   printf "$steps"
 }
 
-#############################################################################
+###############################################################################
 
 function chain_commands() {
   for cmd in ${commands[@]}; do
@@ -123,6 +120,8 @@ function chain_commands() {
 }
 
 function main() {
+  [[ $# -eq 0 ]] && usage && exit 0
+
   local steps=1 in_prompt=0 raw=0 
   local commands=() options=()
 
@@ -137,7 +136,7 @@ function main() {
         -r | --raw) raw=1;;
         *)
           if [[ -z $1 ]]; then
-            utility bash print-status -i error "Invalid options: $arg"
+            print-status -i error "Invalid options: $arg"
             usage && exit 1
           fi
           ;;
@@ -156,7 +155,7 @@ function main() {
     commands[i]="seq_${commands[i]/-/_}"
 
     if ! command -v "${commands[i]%%:*}" &> /dev/null; then
-      utility bash print-status -i error "Invalid command: ${commands[i]}"
+      print-status -i error "Invalid command: ${commands[i]}"
       usage && exit 1
     fi
   done
@@ -164,4 +163,15 @@ function main() {
   chain_commands
 }
 
-main "$@"
+#############################################################################
+
+eval "function $NAME() { utility bash $NAME \"\$@\"; }"
+
+# Sourcing this file will expose the same functions used by this command.
+# Explicitly exporting these here will make them available in all subshells.
+if is_sourced; then
+  export -f $NAME
+  return 0
+else
+  main "$@"
+fi
diff --git a/bin/utilities/bash/decrypt b/bin/utilities/bash/decrypt
--- a/bin/utilities/bash/decrypt
+++ b/bin/utilities/bash/decrypt
@@ -1,8 +1,9 @@
 #!/usr/bin/env bash
 
-NAME=$(basename $0)
 MYTMPDIR=$(mktemp -d 2>/dev/null || mktemp -d -t "$DOTFILES_STATE_PATH/tmp/$NAME.XXXXXX")
 trap 'error_handler' ERR
+
+NAME=$(basename "$(is_sourced && echo ${BASH_SOURCE[0]} || echo "$0")")
 
 usage() {
   echo
@@ -23,8 +24,7 @@ usage() {
   echo "                              (NOTE: No spaces!)"
 }
 
-# Fail early if no arguments are given.
-[[ $# -eq 0 ]] && usage && exit 1
+###############################################################################
 
 function call_openssl() {
   local string="openssl aes-256-cbc -d -pbkdf2"
@@ -41,6 +41,9 @@ function call_openssl() {
 }
 
 function main() {
+  # Fail early if no arguments are given.
+  [[ $# -eq 0 ]] && usage && exit 0
+
   local input output passkey
 
   while [[ $# -gt 0 ]]; do
@@ -52,7 +55,7 @@ function main() {
     -f | --file)
       shift
       if [[ ! -f $1 ]]; then
-        utility bash print-status -i error "Input file not found: $1"
+        print-status -i error "Input file not found: $1"
         usage && exit 1
       fi
       input="$1"
@@ -77,18 +80,29 @@ function main() {
       shift
       ;;
     *)
-      utility bash print-status -i error "Invalid option: $1"
+      print-status -i error "Invalid option: $1"
       usage && exit 1
       ;;
     esac
   done
 
   if [[ -z $input ]]; then
-    utility bash print-status -i error "You need to provide a string or file to encrypt."
+    print-status -i error "You need to provide a string or file to encrypt."
     usage && exit 1
   fi
 
   $(call_openssl)
 }
 
-main "$@"
+#############################################################################
+
+eval "function $NAME() { utility bash $NAME \"\$@\"; }"
+
+# Sourcing this file will expose the same functions used by this command.
+# Explicitly exporting these here will make them available in all subshells.
+if is_sourced; then
+  export -f $NAME
+  return 0
+else
+  main "$@"
+fi
diff --git a/bin/utilities/bash/print-status b/bin/utilities/bash/print-status
--- a/bin/utilities/bash/print-status
+++ b/bin/utilities/bash/print-status
@@ -4,9 +4,11 @@
 
 trap 'error_handler' ERR
 
+NAME=$(basename "$(is_sourced && echo ${BASH_SOURCE[0]} || echo "$0")")
+
 usage() {
   echo
-  echo "Usage: $(basename $0) [-h|--help] <options> <message>"
+  echo "Usage: $NAME [-h|--help] <options> <message>"
   echo
   echo "Options:"
   echo "  -h|--help                   Show this help message and exit."
@@ -21,8 +23,7 @@ usage() {
   echo "  -nc|--no-clear              Does not clear the line before output."
 }
 
-# Fail early if no arguments are given.
-[[ $# -eq 0 ]] && usage && exit 1
+#############################################################################
 
 function icon() {
   case "$icon" in
@@ -40,7 +41,11 @@ function newline() {
 }
 
 function main() {
+  # Fail early if no arguments are given.
+  [[ $# -eq 0 ]] && usage && exit 0
+
   local newline=1 clearline=1 icon="pending" message prefix
+  STATUS_AFFIX=""
 
   while [[ $# -gt 0 ]]; do
     case $1 in
@@ -74,16 +79,15 @@ function main() {
       if [[ -z $message ]]; then
         message="$1"
       else
-        basename "error" "Invalid option: $1\n"
-        usage
-        exit 1
+        print-status -i error "Invalid option: $1"
+        usage && exit 1
       fi
       shift
       ;;
     esac
   done
 
-  [[ $clearline -eq 1 ]] && utility bash cursor move-start clear-line
+  [[ $clearline -eq 1 ]] && cursor move-start clear-line
 
   [[ -n $prefix ]] && result="$prefix"
   [[ -n $icon ]] && result+="$(icon) "
@@ -91,4 +95,15 @@ function main() {
   printf "$result"
 }
 
-main "$@"
+#############################################################################
+
+eval "function $NAME() { utility bash $NAME \"\$@\"; [ -n "\${STATUS_AFFIX}" ] && \$STATUS_AFFIX ; }"
+
+# Sourcing this file will expose the same functions used by this command.
+# Explicitly exporting these here will make them available in all subshells.
+if is_sourced; then
+  export -f $NAME
+  return 0
+else
+  main "$@"
+fi
diff --git a/bin/utilities/bash/prompt-user b/bin/utilities/bash/prompt-user
--- a/bin/utilities/bash/prompt-user
+++ b/bin/utilities/bash/prompt-user
@@ -3,9 +3,11 @@
 trap 'error_handler' ERR
 trap 'interrupt_handler' SIGINT
 
+NAME=$(basename "$(is_sourced && echo ${BASH_SOURCE[0]} || echo "$0")")
+
 usage() {
   echo
-  echo "Usage: $(basename $0) [-h|--help] [options] <question>"
+  echo "Usage: $NAME [-h|--help] [options] <question>"
   echo
   echo "Options:"
   echo "  -h|--help                Show this help message and exit."
@@ -15,6 +17,8 @@ usage() {
   echo "  -c|--confirm             Pressing any key will confirm the prompt."
   echo "  -i|--indent <string>     Adds a string to the beginning of the prompt."
 }
+
+###############################################################################
 
 function basic() {
   local input
@@ -92,7 +96,12 @@ function prompt_line() {
   printf "$indent$string"
 }
 
+###############################################################################
+
 function main() {
+  # Fail early if no arguments are given.
+  [[ $# -eq 0 ]] && usage && exit 0
+
   local prompt_function="basic" question default indent
 
   while [[ $# -gt 0 ]]; do
@@ -127,7 +136,7 @@ function main() {
       if [[ -z $question ]]; then
         question="$1"
       else
-        utility bash print-status -i error "Invalid option: $1"
+        print-status -i error "Invalid option: $1"
         usage && exit 1
       fi
       shift
@@ -136,11 +145,22 @@ function main() {
   done
 
   if [[ -z $question ]]; then
-    utility bash print-status -i error "You need to provide a question to ask."
+    print-status -i error "You need to provide a question to ask."
     usage && exit 1
   fi
 
   eval $prompt_function
 }
 
-main "$@"
+#############################################################################
+
+eval "function $NAME() { utility bash $NAME \"\$@\"; }"
+
+# Sourcing this file will expose the same functions used by this command.
+# Explicitly exporting these here will make them available in all subshells.
+if is_sourced; then
+  export -f $NAME
+  return 0
+else
+  main "$@"
+fi
diff --git a/bin/utilities/bash/salt b/bin/utilities/bash/salt
--- a/bin/utilities/bash/salt
+++ b/bin/utilities/bash/salt
@@ -5,7 +5,7 @@
 #
 # https://gist.github.com/ConnerWill/d4b6c776b509add763e17f9f113fd25b
 #
-NAME=$(basename "$0")
+NAME=$(basename "$(is_sourced && echo ${BASH_SOURCE[0]} || echo "$0")")
 
 trap 'error_handler' ERR
 
@@ -23,17 +23,6 @@ usage() {
   echo "  -h|--help             Show this help message and exit."
   #echo "  -s|--silent          Suppress feedback messages where possible."
 }
-
-# Fail early if no arguments are given.
-[[ $# -eq 0 ]] && usage && exit 1
-
-#############################################################################
-
-cursor() { utility bash cursor "$@"; }
-encrypt() { utility bash encrypt "$@"; }
-decrypt() { utility bash decrypt "$@"; }
-print-status() { utility bash print-status "$@"; }
-prompt-user() { utility bash prompt-user "$@"; }
 
 #############################################################################
 
@@ -132,6 +121,9 @@ function current() {
 #############################################################################
 
 function main() {
+  # Fail early if no arguments are given.
+  [[ $# -eq 0 ]] && usage && exit 0
+
   local command options passkey
   options=()
 
@@ -150,7 +142,7 @@ function main() {
         #-s | --silent) silent=1;;
         -*)
           if [[ -z $1 ]]; then
-            utility bash print-status -i error "Invalid options: $arg"
+            print-status -i error "Invalid options: $arg"
             usage && exit 1
           fi
           ;;
@@ -164,11 +156,22 @@ function main() {
   command="${@: -1}"
 
   if ! command -v "$command" &> /dev/null; then
-    utility bash print-status -i error "Invalid command: $command"
+    print-status -i error "Invalid command: $command"
     usage && exit 1
   fi
 
   $command
 }
 
-main "$@"
+#############################################################################
+
+eval "function $NAME() { utility bash $NAME \"\$@\"; }"
+
+# Sourcing this file will expose the same functions used by this command.
+# Explicitly exporting these here will make them available in all subshells.
+if is_sourced; then
+  export -f $NAME
+  return 0
+else
+  main "$@"
+fi
