Make sure everything use the extracted print-status function.

diff --git a/bin/utilities/bash/prompt-user b/bin/utilities/bash/prompt-user
--- a/bin/utilities/bash/prompt-user
+++ b/bin/utilities/bash/prompt-user
@@ -88,9 +88,8 @@ function main() {
       if [[ -z $question ]]; then
         question="$1"
       else
-        show_status "error" "Invalid option: $1\n"
-        usage
-        exit 1
+        utility bash print-status -i error "Invalid option: $1"
+        usage && exit 1
       fi
       shift
       ;;
@@ -98,9 +97,8 @@ function main() {
   done
 
   if [[ -z $question ]]; then
-    show_status "error" "You need to provide a question to ask.\n"
-    usage
-    exit 1
+    utility bash print-status -i error "You need to provide a question to ask."
+    usage && exit 1
   fi
 
   eval $prompt_function
diff --git a/bin/utilities/misc/bitwarden b/bin/utilities/misc/bitwarden
--- a/bin/utilities/misc/bitwarden
+++ b/bin/utilities/misc/bitwarden
@@ -58,21 +58,21 @@ function cache_vault_items() {
   ITEMS=
   export ITEMS_CACHE_FILE=$(mktemp)
 
-  show_status "pending" "Loading items from vault(s) ... "
+  utility bash print-status -n "Loading items from vault(s) ... "
 
   if [[ -n "$filter" ]]; then
     if ! ITEMS=$(bw list items --search "$filter" --session "$(session_token)" 2>/dev/null); then
-      show_status "error" "Could not load items or operation timed out."
-      echo && exit 1
+      utility bash print-status -i error "Could not load items or operation timed out."
+      exit 1
     fi
   else
     if ! ITEMS=$(bw list items --session "$(session_token)" 2>/dev/null); then
-      show_status "error" "Could not load items or operation timed out."
-      echo && exit 1
+      utility bash print-status -i error "Could not load items or operation timed out."
+      exit 1
     fi
   fi
 
-  show_status "ok" "Items loaded from vault(s)."
+  utility bash print-status -n -i ok "Items loaded from vault(s)."
   echo "$ITEMS" >"$ITEMS_CACHE_FILE"
   openssl aes-256-cbc -a -salt -pbkdf2 -in $ITEMS_CACHE_FILE -out $ITEMS_CACHE_FILE.enc -k $DOTFILES_ENCRYPTION_KEY
   echo
@@ -99,9 +99,8 @@ function main() {
       exit 0
       ;;
     *)
-      show_status "error" "Invalid option: $1"
-      usage
-      exit 1
+      utility bash print-status -i error "Invalid option: $1"
+      usage && exit 1
       ;;
     esac
   done
diff --git a/bin/utilities/misc/decrypt b/bin/utilities/misc/decrypt
--- a/bin/utilities/misc/decrypt
+++ b/bin/utilities/misc/decrypt
@@ -47,9 +47,8 @@ function main() {
       if [[ -z $input ]]; then
         input="$1"
       else
-        show_status "error" "Invalid option: $1\n"
-        usage
-        exit 1
+        utility bash print-status -i error "Invalid option: $1"
+        usage && exit 1
       fi
       shift
       ;;
@@ -60,16 +59,14 @@ function main() {
     if [[ -p /dev/stdin ]]; then
       input=$(cat /dev/stdin)
     else
-      show_status "error" "You need to provide an input string to decrypt.\n"
-      usage
-      exit 1
+      utility bash print-status -i error "You need to provide an input string to decrypt."
+      usage && exit 1
     fi
   fi
 
   if [[ $file -eq 1 ]] && [[ ! -f $input ]]; then
-    show_status "error" "Input file not found: $input\n"
-    usage
-    exit 1
+    utility bash print-status -i error "Input file not found: $input"
+    usage && exit 1
   fi
 
   local cmd="openssl aes-256-cbc -a -d -pbkdf2"
