Rename print-user and prompt-user to variants with an underscore so bash in POSIX mode does not throw a fit when trying to import those function definitions. I got those two as errors when running `bash --posix -c true`.

diff --git a/bin/utilities/bash/salt b/bin/utilities/bash/salt
--- a/bin/utilities/bash/salt
+++ b/bin/utilities/bash/salt
@@ -27,10 +27,10 @@ usage() {
 #############################################################################
 
 function reset() {
-  print-status "Resetting salt and all encrypted files ..."
+  print_status "Resetting salt and all encrypted files ..."
   rm -f "$DOTFILES_STATE_PATH"/*.enc
   cursor move-up move-start
-  print-status -i ok "Salt and encrypted files have been reset.\n"
+  print_status -i ok "Salt and encrypted files have been reset.\n"
   echo "    Please source ~/.bashrc (\`s\`) or restart your shell to apply changes."
   echo
 }
@@ -47,26 +47,26 @@ function generate() {
 
   # So we know where to restore to after a variable number of attempts.
   if [[ $looping -eq 0 ]]; then
-    print-status "Generating new salt ..." >&2
+    print_status "Generating new salt ..." >&2
     cursor save
   fi
 
   if [[ -z "$passkey" ]]; then
-    passkey=$(prompt-user -i "$icon " -m "Enter your desired password: ") >&2
+    passkey=$(prompt_user -i "$icon " -m "Enter your desired password: ") >&2
   fi
 
-  pass_confirmation=$(prompt-user -i "$(pending) " -m  "Confirm your entered password: ") >&2
+  pass_confirmation=$(prompt_user -i "$(pending) " -m  "Confirm your entered password: ") >&2
 
   if [[ ${#passkey} -lt 3 ]]; then
     cursor restore clear-down >&2
-    print-status -i error "Passkey must be at least 3 characters long."
+    print_status -i error "Passkey must be at least 3 characters long."
     generate -l
     return
   fi
 
   if [[ "$passkey" != "$pass_confirmation" ]]; then
     cursor restore clear-down >&2
-    print-status -i error "Mismatched passwords, try again." >&2
+    print_status -i error "Mismatched passwords, try again." >&2
     generate -l
     return
   fi
@@ -76,9 +76,9 @@ function generate() {
   cursor restore clear-down clear-up >&2
 
   if [[ $? -eq 0 ]]; then
-    print-status -i ok "Encrypted salt is ready." >&2
+    print_status -i ok "Encrypted salt is ready." >&2
   else
-    print-status -i error "Decrypt failed; try again or press Ctrl-c to abort." >&2
+    print_status -i error "Decrypt failed; try again or press Ctrl-c to abort." >&2
     generate -l
     return
   fi
@@ -90,7 +90,7 @@ function decrypt_salt() {
 
   if [[ -z "$passkey" ]]; then
     icon="$(pending)"
-    passkey=$(prompt-user -i "$icon " -m "Enter your salt passkey: ")
+    passkey=$(prompt_user -i "$icon " -m "Enter your salt passkey: ")
   fi
 
   if decrypt -p "$passkey" -f "$DOTFILES_SALT_PATH" 2>/dev/null; then
@@ -142,7 +142,7 @@ function main() {
         #-s | --silent) silent=1;;
         -*)
           if [[ -z $1 ]]; then
-            print-status -i error "Invalid options: $arg"
+            print_status -i error "Invalid options: $arg"
             usage && exit 1
           fi
           ;;
@@ -156,7 +156,7 @@ function main() {
   command="${@: -1}"
 
   if ! command -v "$command" &> /dev/null; then
-    print-status -i error "Invalid command: $command"
+    print_status -i error "Invalid command: $command"
     usage && exit 1
   fi
 
