Be more consistent in my path names (ie. use *_HOME instead of _PATH for XDG-realted configuration paths).

diff --git a/setup/dots b/setup/dots
--- a/setup/dots
+++ b/setup/dots
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 set -e
 
-source "$DOTFILES_CONFIG_PATH"/env
+source "$DOTFILES_CONFIG_HOME"/env
 
-log_file="$DOTFILES_STATE_PATH"/dots.log
+log_file="$DOTFILES_STATE_HOME"/dots.log
 [ ! -f "$log_file" ] && touch "$log_file"
 
 usage() {
@@ -41,25 +41,25 @@ logs() {
 }
 
 install() {
-  "$DOTFILES_PATH"/setup/install
+  "$DOTFILES_REPO_HOME"/setup/install
 }
 
 update() {
   error_occurred=0
 
   # Check for uncommitted changes and exit gracefully if so.
-  if ! git -C "$DOTFILES_PATH" diff-files --quiet; then
+  if ! git -C "$DOTFILES_REPO_HOME" diff-files --quiet; then
     $print_status -i error "There are uncommitted changes in your dotfiles. Please commit or stash them before updating:"
     echo
-    git -C "$DOTFILES_PATH" st
+    git -C "$DOTFILES_REPO_HOME" st
     exit 1
   fi
 
   # Pull the latest changes
   $print_status -n "Pulling in changes ..."
 
-  if git -C "$DOTFILES_PATH" fetch origin >/dev/null; then
-    if ! git -C "$DOTFILES_PATH" merge --no-commit origin/"$(git -C "$DOTFILES_PATH" b)" &>>"$log_file"; then
+  if git -C "$DOTFILES_REPO_HOME" fetch origin >/dev/null; then
+    if ! git -C "$DOTFILES_REPO_HOME" merge --no-commit origin/"$(git -C "$DOTFILES_REPO_HOME" b)" &>>"$log_file"; then
       error_occurred=1
     fi
   else
@@ -70,7 +70,7 @@ update() {
   if [ $error_occurred -eq 0 ]; then
     $print_status -i ok "Files updated to latest version"
     $print_status -n "Running installer ..."
-    "$DOTFILES_PATH"/setup/install &>>"$log_file" || error_occurred=1
+    "$DOTFILES_REPO_HOME"/setup/install &>>"$log_file" || error_occurred=1
   fi
 
   # Handle final status
diff --git a/setup/install b/setup/install
--- a/setup/install
+++ b/setup/install
@@ -1,22 +1,30 @@
 #!/usr/bin/env bash
 set -e
 
-readonly DOTBOT_DIR="dotbot"
-DOTFILES_PATH="$(dirname "$(dirname "$(realpath "$0")")")"
-readonly DOTFILES_PATH
+function fail {
+  printf "%s\n" "$1" >&2
+  exit "${2-1}"
+}
+
+[ -z "${BASH_VERSION:-}" ] && fail "Bash is required to interpret this script."
+
+DOTFILES_REPO_HOME="$(dirname "$(dirname "$(realpath "$0")")")"
+readonly DOTFILES_REPO_HOME
+dotbot_path="$DOTFILES_REPO_HOME/dotbot"
+readonly dotbot_path
 
 # Trying to adhere to the XDG Base Directory Specification.
-source "$DOTFILES_PATH/bash/env/xdg.sh"
+source "$DOTFILES_REPO_HOME/bash/env/xdg.sh"
 
 # Get dotbot installed
-git -C "$DOTFILES_PATH/$DOTBOT_DIR" submodule sync --quiet --recursive
-git -C "$DOTFILES_PATH/$DOTBOT_DIR" submodule update --init --recursive
+git -C "$dotbot_path" submodule sync --quiet --recursive
+git -C "$dotbot_path" submodule update --init --recursive
 
 # Activate dotbot with the install configuration
-"$DOTFILES_PATH/$DOTBOT_DIR/bin/dotbot" -d "$DOTFILES_PATH" -c "$DOTFILES_PATH/setup/install.conf.yaml" "${@}"
+"$dotbot_path/bin/dotbot" -d "$DOTFILES_REPO_HOME" -c "$DOTFILES_REPO_HOME/setup/install.conf.yaml" "${@}"
 
-if [ ! -f "$DOTFILES_CONFIG_PATH"/env ]; then
-  "$DOTFILES_PATH"/setup/env_wizard || touch "$DOTFILES_CONFIG_PATH"/env
+if [ ! -f "$DOTFILES_CONFIG_HOME/env" ]; then
+  "$DOTFILES_REPO_HOME/setup/env_wizard" || touch "$DOTFILES_CONFIG_HOME/env"
 fi
 
 # Create an executable that allows us to update our dotfiles, among other
@@ -24,7 +32,7 @@ fi
 dots_path="$XDG_BIN_HOME/dots"
 
 if [ ! -f "$dots_path" ]; then
-  ln -s "$DOTFILES_PATH"/setup/dots "$dots_path"
+  ln -s "$DOTFILES_REPO_HOME/setup/dots" "$dots_path"
   chmod +x "$dots_path"
   $dots_path
   echo
