setup/env_wizard: Change how interrupts are handled between the parent and subscript.

diff --git a/setup/env_wizard b/setup/env_wizard
--- a/setup/env_wizard
+++ b/setup/env_wizard
@@ -1,7 +1,13 @@
 #!/usr/bin/env bash
 
 # Gracefully handle Ctrl-C to get out of this thing.
-trap 'printf "\nAborted.\n"; exit 1' SIGINT
+handle_interrupt() {
+  if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
+    printf "\nAborted.\n"
+    exit 1
+  fi
+}
+trap handle_interrupt SIGINT
 
 # Function to prompt for input with a default value
 prompt() {
@@ -64,7 +70,7 @@ else
     echo ""
 
     # Check if Bitwarden CLI is logged in
-    source $setup_path/unlock_bw
+    source $setup_path/unlock_bw || exit 1
 
     # We repeat the check for the session var, because if we don't have it here
     # something went wrong.
diff --git a/setup/unlock_bw b/setup/unlock_bw
--- a/setup/unlock_bw
+++ b/setup/unlock_bw
@@ -4,7 +4,13 @@
 # This is because it exports the BW_SESSION variable to the current shell.
 
 # Gracefully handle Ctrl-C to get out of this thing.
-trap 'printf "\nAborted.\n"; return 1' SIGINT
+handle_interrupt() {
+  if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
+    printf "\nAborted.\n"
+    exit 1
+  fi
+}
+trap handle_interrupt SIGINT
 
 # This only needs to be shown once. The recursive bit just tries to unlock
 # until successful.
