setup/env_wizard: Add setup/unlock_bw and use it in the wizard to allow for a recursive master password loop until success.

diff --git a/setup/env_wizard b/setup/env_wizard
--- a/setup/env_wizard
+++ b/setup/env_wizard
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+# Gracefully handle Ctrl-C to get out of this thing.
+trap 'printf "\nAborted.\n"; exit 1' SIGINT
+
 # Function to prompt for input with a default value
 prompt() {
   local var_name="$1"
@@ -30,7 +33,8 @@ echo ""
 
 # Derive the dotfiles' absolute path so we always have a sensible default for 
 # the ~/.env file.
-dotfiles_derived_path=$(dirname $(dirname $(realpath "$0")))
+setup_path="$(dirname $(realpath "$0"))"
+dotfiles_derived_path=$(dirname $setup_path)
 env_file="${HOME}/.env"
 
 # Load existing .env if available
@@ -60,28 +64,29 @@ else
     echo ""
 
     # Check if Bitwarden CLI is logged in
-    printf "Checking Bitwarden status ... "
-    if ! bw status | grep -q "locked"; then
-      echo "Bitwarden is locked or not logged in. Please run 'bw unlock' before continuing."
-      exit 1
+    source $setup_path/unlock_bw
+
+    # We repeat the check for the session var, because if we don't have it here
+    # something went wrong.
+    if [[ -z $BW_SESSION ]]; then
+      echo "Bitwarden unlock unsuccessful, proceeding without Bitwarden ..."
+    else
+      printf "Syncing with Bitwarden vaults ... "
+      bw sync
+      echo ""
     fi
-    printf "OK!"
-    echo ""
-    echo ""
 
     OWNER_NAME=$(prompt "OWNER_NAME" "Enter your first and last name" "")
     GITHUB_EMAIL=$(prompt "GITHUB_EMAIL" "Enter the email address you log into Github with" "")
 
-    printf "Grabbing Bitwarden data ... "
+    printf "Fetching Bitwarden data ... "
     owner_data=$(bw list items --search "$OWNER_NAME" | jq '.[] | select(.identity != null)')
     bitwarden_data=$(bw get item "$GITHUB_EMAIL")
-    printf "OK!"
-    echo ""
-    echo ""
 
     GITHUB_USERNAME="$(echo $bitwarden_data | jq -r '.fields[] | select(.name == "Public username").value')"
     GITHUB_API_TOKEN=$(echo $bitwarden_data | jq -r '.fields[] | select(.name == "Github API Token") | .value')
     GPG_SIGNING_KEY=$(echo $owner_data | jq -r '.fields[] | select(.name == "GPG signing key").value')
+    printf "OK!\n\n"
   else
     echo "Skipping Bitwarden."
   fi
@@ -97,9 +102,9 @@ GITHUB_API_TOKEN=$(prompt "GITHUB_API_TOKEN" "Enter your Github API Token" "${GI
 GPG_SIGNING_KEY=$(prompt "GPG_SIGNING_KEY" "Enter your GPG signing key" "${GPG_SIGNING_KEY}")
 
 # Write to .env
-cat > "$env_file" <<EOF
+cat <<EOF >>$env_file
 # This file is generated by $dotfiles_derived_path/setup/env_wizard.
-# If you add your own global ENV vars below, remember to backport them to it.
+# If you add your own global ENV vars below, remember to backport them to that script.
 OWNER_NAME="$OWNER_NAME"
 REPO_NAMESPACE="$(grealpath -m "${REPO_NAMESPACE/#\~/$HOME}")"
 DOTFILES_PATH="$dotfiles_derived_path"
