Another intermediary commit because I'm only making bits and bobs of progress every time.

diff --git a/setup/env_wizard b/setup/env_wizard
--- a/setup/env_wizard
+++ b/setup/env_wizard
@@ -12,72 +12,55 @@ export DOTFILES_STATE_PATH="${HOME}/.local/state/dots"
 bitwarden_cmd="$DOTFILES_PATH/bin/utilities/misc/bitwarden"
 
 [[ -f $DOTFILES_PATH/bash/helpers.sh ]] && source $DOTFILES_PATH/bash/helpers.sh
-trap interrupt_handler SIGINT
+trap 'clear && interrupt_handler' SIGINT
 
-# Function to prompt for input with a default value
-function prompt() {
-  local var_name="$1"
-  local prompt_text="$2"
-  local default_value="$3"
-  local input
-  read -p "$(pending) ${prompt_text} [${default_value}]: " input
-  echo "${input:-$default_value}"
+function print-status() {
+  utility bash print-status "$@"
 }
 
 function separator() {
-  echo "——————————"
+  printf "────¦"
+  printf '%.s─' $(seq 6 $(tput cols))
+}
+
+function fecho() {
+  printf "    ¦ %s" "$1"
 }
 
 function intro() {
-  echo
-  echo "    |"
-  echo "    | This script will help you set up your environment variables."
-  echo "    | Press Enter to confirm suggested values."
-  echo "    | Press Ctrl + c at any time to abort."
-  echo "    |"
-  echo
-
-  while true; do
-    read -n1 -p "Press any key to continue ... " ok
-    if [[ -n $ok ]]; then 
-      clear_line && separator
-      break
-    fi
-  done
+  echo "    ¦"
+  echo "    ¦ This script will help you set up your environment variables."
+  echo "    ¦ Press Enter to confirm suggested values."
+  echo "    ¦ Press Ctrl + c at any time to abort."
+  echo "    ¦"
 }
 
 function salt_intro() {
-  echo
-  echo "    |"
-  echo "    | Some utility commands like encrypt/decrypt require a password-protected salt."
-  echo "    | Every time you log into your shell, you will be prompted for this password."
-  echo "    |"
-  echo
+  echo "    ¦"
+  echo "    ¦ Some utility commands like encrypt/decrypt require a password-protected salt."
+  echo "    ¦ Every time you log into your shell, you will be prompted for this password."
+  echo "    ¦"
 }
 
 function bitwarden_data_intro() {
-  echo
-  echo "    |"
-  echo "    | Some utility commands like encrypt/decrypt require a password-protected salt."
-  echo "    | Every time you log into your shell, you will be prompted for this password."
-  echo "    |"
-  echo
+  echo "    ¦"
+  echo "    ¦ Some utility commands like encrypt/decrypt require a password-protected salt."
+  echo "    ¦ Every time you log into your shell, you will be prompted for this password."
+  echo "    ¦"
 }
 
 function bitwarden_data_intro() {
-  echo
-  echo "    |"
-  echo "    | You need the following two items ready in Bitwarden:"
-  echo "    |"
-  echo "    | 1. An item of the Identity type, containing your first and last name."
-  echo "    |    a. A custom field entry on the Identity item named 'GPG signing key'"
-  echo "    |"
-  echo '    | 2. An item of the Login type, named "Github", containing:'
-  echo "    |    a. The Username login credential that matches your Github e-mail address"
-  echo "    |    b. A custom field entry named 'Public username'"
-  echo "    |    c. A custom field entry named 'Personal access token'"
-  echo "    |"
-  echo
+  echo "    ¦"
+  echo "    ¦ You need the following two items ready in Bitwarden:"
+  echo "    ¦"
+  echo "    ¦ 1. An item of the Identity type, containing your first and last name."
+  echo "    ¦    a. A custom field entry on the Identity item named 'GPG signing key'"
+  echo "    ¦"
+  echo '    ¦ 2. An item of the Login type, named "Github", containing:'
+  echo "    ¦    a. The Username login credential that matches your Github e-mail address"
+  echo "    ¦    b. A custom field entry named 'Public username'"
+  echo "    ¦    c. A custom field entry named 'Personal access token'"
+  echo "    ¦"
 }
 
 function bitwarden_prompt() {
@@ -87,9 +70,9 @@ function bitwarden_prompt() {
     read -n1 -p "Would you like to use Bitwarden to retrieve your environment variables? (y/n) " bitwarden
 
     case $bitwarden in
-      [Yy]* ) show_status "ok" "Using Bitwarden." && echo && return 0;;
-      [Nn]* ) show_status "error" "Not using Bitwarden." && echo && return 1;;
-      * ) show_status "pending" "Please answer `tput smul`Y`tput rmul`es or `tput smul`N`tput rmul`o. ";;
+      [Yy]* ) print-status -i ok "Using Bitwarden." && return 0;;
+      [Nn]* ) print-status -i error "Not using Bitwarden." && return 1;;
+      * ) print-status -n "Please answer `tput smul`Y`tput rmul`es or `tput smul`N`tput rmul`o. ";;
     esac
   done
 
@@ -101,8 +84,7 @@ function bitwarden_requirements() {
     # TODO: This assumes all vars are accounted for with values.
     # Probably need to check every individual var instead.
     source "$env_file"
-    show_status "ok" "Loaded environment variables from $env_file."
-    echo
+    print-status -p "$(fecho)" -i ok "Loaded environment variables from $env_file."
   else
     if bitwarden_prompt; then
       ensure_brew_dependency jq 'bitwarden-cli:bw'
@@ -110,6 +92,8 @@ function bitwarden_requirements() {
     fi
   fi
 
+  fecho
+  printf "\n\n"
   bitwarden_data_wizard
 }
 
@@ -124,10 +108,9 @@ function load_env_data_from_bitwarden() {
   # We repeat the check for the session var, because if we don't have it here
   # something went wrong.
   if [[ -n $BW_SESSION ]]; then
-    show_status "pending" "Syncing with Bitwarden vaults ... "
+    print-status -n "Syncing with Bitwarden vaults ... "
     bw sync --quiet
-    show_status "ok" "Bitwarden vaults synced."
-    echo
+    print-status -i ok "Bitwarden vaults synced."
   fi
 
   #OWNER_NAME="$(
@@ -148,7 +131,7 @@ function load_env_data_from_bitwarden() {
   export GITHUB_EMAIL=$(utility bash prompt-user -d "$GITHUB_EMAIL" "Enter the e-mail address you log into Github with")
   clear_prompt_line
 
-  show_status "pending" "Preparing data from vault(s) ... "
+  print-status -n "Preparing data from vault(s) ... "
   owner_data=$(bw list items --session "$BW_SESSION" --search "$OWNER_NAME" | jq '.[] | select(.identity != null)')
   bitwarden_data=$(bw get item --session "$BW_SESSION" "$GITHUB_EMAIL")
 
@@ -162,8 +145,7 @@ function load_env_data_from_bitwarden() {
   GITHUB_USERNAME="$(echo $bitwarden_data | jq -r '.fields[] | select(.name == "Public username").value')"
   GITHUB_PERSONAL_ACCESS_TOKEN=$(echo $bitwarden_data | jq -r '.fields[] | select(.name == "Personal access token") | .value')
   GPG_SIGNING_KEY=$(echo $owner_data | jq -r '.fields[] | select(.name == "GPG signing key").value')
-  show_status "ok" "Vault data prepared. "
-  echo
+  print-status -i ok "Vault data prepared."
 }
 
 function bitwarden_data_wizard() {
@@ -191,12 +173,11 @@ function bitwarden_data_wizard() {
 
   # Check if the REPO_NAMESPACE path exists, and create it if not.
   if [[ ! -d $REPO_NAMESPACE ]]; then
-    show_status "pending" "Creating $REPO_NAMESPACE ... "
+    print-status -n "Creating $REPO_NAMESPACE ... "
     # You want to use `grealpath` here to correctly resolve the tilde in the path
     # and prevent bash from creating a directory named "~". -.-
     #mkdir -p "$(grealpath $REPO_NAMESPACE)"
-    show_status "ok" "Created $REPO_NAMESPACE."
-    echo
+    print-status -i ok "Created $REPO_NAMESPACE."
   fi
 }
 
@@ -208,20 +189,21 @@ salt_requirements() {
   local pass_confirmation=$(utility bash prompt-user -m  "Confirm your entered password: ")
   echo
 
-  if [[ $pass != $pass_confirmation ]]; then
-    show_status "error" "Passwords do not match. Please try again."
-    #clear_line -n 6
-    for i in {1..10}; do printf '\033[F\033[K'; done
+  if [[ -z $pass ]] || [[ -z $pass_confirmation ]] || [[ $pass != $pass_confirmation ]]; then
+    print-status --prefix "$(fecho)" -i error "Passwords do not match. Please try again."
+    for i in {1..9}; do printf '\033[F\033[K'; done
     printf "\033[J"
-    salt_requirements
+    salt_requirements 1
     return
   fi
 
   # Generate a salt and encrypt it with the given password.
   echo $(openssl rand -base64 32 | utility misc encrypt -p "$pass") > "$DOTFILES_STATE_PATH/salt"
-  #clear_line -n 10
+
   for i in {1..4}; do printf '\033[F\033[K'; done
-  show_status "ok" "Salt successfully saved.\n"
+  print-status -p "$(fecho)" -i ok "Salt successfully saved."
+  fecho
+
   echo
   separator
   echo
@@ -255,12 +237,20 @@ EOF
 
 function main() {
   intro
+
+  while true; do
+    read -n1 -p "Press any key to continue ... " ok
+    if [[ -n $ok ]]; then 
+      clear_line && separator
+      break
+    fi
+  done
+
   salt_requirements
   bitwarden_requirements
-  write_env_files
+  #write_env_files
 
-  show_status "ok" "All done!"
-  echo
+  print-status -i ok "All done!"
   echo
   echo "Environment variables written to these files:"
   echo "  $gitconfig_env_file"
